### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by Ahmaaadm** [mostafa-fallaha/heart-disease-prediction#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://heart-disease-prediction-xg9z5ycbwhuyasqu458hav.streamlit.app/mostafa-fallaha/heart-disease-prediction/main/app2.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by mostafa-fallaha** [comment]
Hey Ahmad,

Thank you so much for letting me know about the resource limit issue on my Streamlit Cloud app. Your heads-up was really helpful. I appreciate you looking out!
